### ISSUE TITLE
RFHUB2 via HTTPS

### ISSUE THREAD

**Issue by damien122** [pbylicki/rfhub2#113]
Hi,

is it possible to use HTTPS in rfhub2?

**Comment by pbylicki** [comment]
Hi @damien122,
Currently it is not available out of the box. If you want to play around, uvicorn supports direct connection via HTTPS and you could run rfhub2 with additional SSL configuration parameters added to uvicorn.run method here: https://github.com/pbylicki/rfhub2/blob/master/rfhub2/__main__.py

You can also put the application behind another layer which would be responsible for TLS termination. This is the approach I would suggest. If you use some platform for deploying containerized applications like Kubernetes/OpenShift it should provide an option to expose your application via HTTPS.
If you do not have it, you could run rfhub2 behind web server like Nginx which could be configured for HTTPS. You should be able to run it whether you use rfhub2 docker image or install Python package directly.

**Comment by damien122** [comment]
@pbylicki thx I will try
