### ISSUE TITLE
Searching starts when at least 3 letters are provided with no info

### ISSUE THREAD

**Issue by mnojek** [pbylicki/rfhub2#127]
When start providing value for search box, at first it only displays "No keywords found" alert until the 3rd character is given. I propose adding a proper information that "You need to provide at least 3 characters for searching to start" or something similar when no more than 2 characters are in the search box. 
![image](https://user-images.githubusercontent.com/7412964/71718043-46cba500-2e1a-11ea-8f03-334ff2e7eacc.png)

**Comment by pbylicki** [comment]
@MaciejWiczk @nojas10 what do you think about changing this to start searching with first character instead?

**Comment by MaciejWiczk** [comment]
That's good idea, espacially having tags in mind, where they can be short, like DB, CI, UI.

**Comment by mnojek** [comment]
I would say that it's not because one letter fits wherever it is used regardless it's a part of the word or not. So it can have some performance overhead when comes to searching all occurrences of a specific letter. Maybe it's better to start with 2? I think we can assume that nobody will use one letter tags.

**Comment by MaciejWiczk** [comment]
You do have a point here, but fortnately search endpoint is paged, so we don't have to worry that much about performance here, I believe.

**Comment by MarcinMaciaszek** [comment]
@pbylicki @MaciejWiczk can I fix it ?

**Comment by pbylicki** [comment]
@MaciejWiczk so what would be the expected fix here? to start searching when there are at least two characters?

**Comment by MaciejWiczk** [comment]
> @MaciejWiczk so what would be the expected fix here? to start searching when there are at least two characters?

@pbylicki yep, that would be right to do. Maybe we could add a note, that search requires at least two characters to begin searching?

**Comment by pbylicki** [comment]
@MaciejWiczk I don't like the idea of the note - i do not recall any example of the page that would use such solution. If we want to handle this one letter scenario somehow I would rather start searching and display any keywords matching this letter, this is how most search engines out there work. In the future we could order the search results by statistics like times_used so we get popular results first.
So I propose to just remove the limit and search if there is any non-whitespace character typed.

**Comment by MaciejWiczk** [comment]
@pbylicki That will be much better than a note, I agree with You.
