### ISSUE TITLE
Add an option to search individual collections

### ISSUE THREAD

**Issue by mnojek** [pbylicki/rfhub2#129]
Searching now works only for the whole content of RFHub. Would be nice to have an option to search from the keywords belonging to specific collection(s).

**Comment by MaciejWiczk** [comment]
This is already there, but not documented. I will add some docs and gif about it

**Comment by pbylicki** [comment]
@MaciejWiczk How about  adding some help icon next to the search bar which would open a modal with instruction on using search with examples? I was thinking that if we would introduce tags and add mechanism to search only by tags it would be even more useful to present available ways of searching

**Comment by MaciejWiczk** [comment]
That would be even better than just docs, splendind idea. Nevertheless improving docs is on me, and I will do that. BTW, I setup [telegram](https://t.me/rfhub2) channel today, so we can discuss all ideas.

**Comment by MaciejWiczk** [comment]
closed with #302
