### ISSUE TITLE
Long names for keyword or collection display issues

### ISSUE THREAD

**Issue by mnojek** [pbylicki/rfhub2#133]
When the collection or keyword name are too long to fit the width of the left-side menu they are not displayed properly.

![image](https://user-images.githubusercontent.com/7412964/71718869-e0945180-2e1c-11ea-813f-800a8a926c35.png)

I propose adding ellipsis (...) at the end of the too long word:

![image](https://user-images.githubusercontent.com/7412964/71719059-6a441f00-2e1d-11ea-83eb-29ddc410cbbe.png)

Or break the word in the place where it meets with the div border:

![image](https://user-images.githubusercontent.com/7412964/71719116-919aec00-2e1d-11ea-8934-d1335d02cf1f.png)

[Here is the example of solution](https://www.codelord.net/2013/08/23/css-tip-overflowing-with-text/).

**Comment by MarcinMaciaszek** [comment]
elipsis (...) and ful ltext on hover would be great :)

**Comment by MarcinMaciaszek** [comment]
Merged and working, close :)
