### ISSUE TITLE
Adding keyword tags to keyword model

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#136]
Adding keyword tags to rfhub would help user with searching for right keywords, and excluding ones not seek, ie. manual keywords. 

Currently tags are excluded from being gathered by cli. Model would need to be extended with additional, optional field of list type, similar to args. Frontend would need to be extended by additional column with tags for keyword table. Perhaps collection table could hold set of tags as well, but that would complicate this feature even more, so I would extract it as separate one.
Tasks list:

- [x] [Model](https://github.com/pbylicki/rfhub2/issues/158) 
- [x] [Search](https://github.com/pbylicki/rfhub2/issues/159)
- [x] [CLI](https://github.com/pbylicki/rfhub2/issues/160)
- [x] [Frontend](https://github.com/pbylicki/rfhub2/issues/161)
- [x] [SQL Migrations](https://github.com/pbylicki/rfhub2/issues/162)
- [x] Tests

**Comment by MarcinMaciaszek** [comment]
@MaciejWiczk It would be great to split it between small issues:
1. Model with migrations
2. Cli
3. API
4. search with frontend
What do you think ?

**Comment by MaciejWiczk** [comment]
I'm all for it! Le't keep this one as parent task, and I will create small subtasks

**Comment by MaciejWiczk** [comment]
Closed by #208, #209, #210, #211
