### ISSUE TITLE
Importing a library which also contains robot files

### ISSUE THREAD

**Issue by idefixcert** [pbylicki/rfhub2#153]
If I import a library which also contains robot files,
the robot files are not imported.

**Comment by MaciejWiczk** [comment]
Hi @idefixcert, if I understood You correctly, You have library with __init__.py, and some .robot files in one directory? That's something I have not foreseen. Rfhub2, when traversing paths is looking for __init__.py file, and if it exists and importing it returns >0 keywords, this directory is treated as directory for single library, and the rest of the files is ommited. This way, app is not importing submodules, but Library as a whole.

**Comment by idefixcert** [comment]
The problem is, there is no keyword in the library itself, I just want use the python setup tool for distributing the robot files via pip.
Is that a common way to do it?

**Comment by MaciejWiczk** [comment]
> The problem is, there is no keyword in the library itself, I just want use the python setup tool for distributing the robot files via pip.

Oh, that's a tricky one. But is it safe to repoduce issue with assumptions I made previosly? I could change app to traverse path further for robot files, even where `__init__.py` exists. That could solve your issue.

**Comment by idefixcert** [comment]
@MaciejWiczk yes with the latest release my issues are fixed
