### ISSUE TITLE
Import a library with 2 classes is not recorgnized

### ISSUE THREAD

**Issue by idefixcert** [pbylicki/rfhub2#154]
I have a library with 2 classes.
This is not recorgnized by the importer.

**Comment by MaciejWiczk** [comment]
Could You provide some minimum code example? There are few ways to create library for RFWK.
Did robot.libdoc create documentation the way You expected?

**Comment by idefixcert** [comment]
Ok I see the thing is that libdoc also not allows that.
So I created a new library.
