### ISSUE TITLE
Add functionality to populate RfHub-new with data

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#2]
This task is about adding functionality to populate RfHub-new as in previous application. There is a need of checking specified folders, with keywords and libraries, which should be added and displayed in application. Adding collections and keywords should be done via API.

**Comment by pbylicki** [comment]
IMO it should be Click CLI application (we already depend on this package) located in rfhub2.cli package structured in such a way that:
- client responsible for communication with REST API (or database if needed before #6 is implemented) should be defined, ideally with one interface that covers both ways of communication (REST/db)
- it would be nice to use the same model for sending data that API uses as incoming data model for parsing and validation (it will be implemented as part of #6).

**Comment by MaciejWiczk** [comment]
I've started looking at Click package. I need some more understanding in regards of making clients for Rest API/DB. For now I know that populating application:
- using DB should happen before app starts
- using Rest API should happen after app starts, so we have working endpoint, obviously

Should those two clients be located in rfhub2.cli? Or maybe somewhere different like rfhub2.clients? Last but not least, should app.py with create_app method be changed into class and incorporate click args, and various startup modes (ie. worked or web, DB or Rest population)

**Comment by pbylicki** [comment]
Once #13 is merged I do not see a point in updating data directly in db, we should use Rest API and assume that web application will be run separately from the job populating the data. With this approach rest client should be just part of the `rfhub2.cli` package. I would make cli only about populating the data, not running the web server so let's leave web server launching code as is for this task.
So in `rfhub2.cli` there is an Click application for populating rfhub2 web server running on provided url that should be run by `python -m rfhub2.cli [any args here]`
Do you agree @MaciejWiczk ?

**Comment by MaciejWiczk** [comment]
Ok, now I have better picture. I see two actions to be taken care of:
- delete row: https://github.com/pbylicki/rfhub-new/blob/master/rfhub2/main.py#. @pbylicki will this lead to change in unit_tests? Or are they independent of that?
- creation of another image with rfhub.cli, because docker endpoint will be different han for whole app.

**Comment by pbylicki** [comment]
The unit tests use the same function, but independently in their setup, so recreating data can be removed from application starting procedure once mechanism for populating data is done.
As for new image I do not think we really need it - at this point you just need to run existing image with custom entrypoint. Also I would assume that for using cli one would want to have it installed directly on the machine or if not - turned into a script or alias for shorter syntax and easier usage. In both cases we can handle it without new image. We can bring it back if we would start build this cli into separate package to reduce number of dependencies - than it would totally make sense.

**Comment by MaciejWiczk** [comment]
Very early changes in #20

**Comment by pbylicki** [comment]
PR #20 finally merged
