### ISSUE TITLE
How to access&check UI of rfhub2?

### ISSUE THREAD

**Issue by fengnex** [pbylicki/rfhub2#251]
When executing command rfhub2 in the console, got the following outputs. I wonder how to access it:
C:\Users\Administrator>rfhub2
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c54a916ec6c8, Initial model
INFO  [alembic.runtime.migration] Running upgrade c54a916ec6c8 -> abee96e78502, create tags column for keyword table

C:\Users\Administrator>
C:\Users\Administrator>
C:\Users\Administrator>
C:\Users\Administrator>rfhub2
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by MaciejWiczk** [comment]
Hi @fengnex, I checked docs and actually, that crucial point is missed. To check UI please go to localhost:8000.

**Comment by fengnex** [comment]
@MaciejWiczk Thank you!
I have run rfhub2 successfully and found that it's really useful. Also, it looks pretty beautiful!
I have thus starred the project!

**Comment by MaciejWiczk** [comment]
Additionally, docs could be extended with additional info:
"You can now access rfhub2 instance at .. . It will be empty - you need to populate it with keyword first! More on that in section <link>
