### ISSUE TITLE
RfHub2 is not displaying more than 100 items in left panel

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#29]
RfHub2 is not displaying more than 190 items in left panel. 
HTR:
run application and populate it
```
for i in {1..500}; do curl -u rfhub:rfhub -X POST "http://localhost:8000/api/v1/collections/" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"name\":\"$i\",\"type\":\"string\",\"version\":\"string\",\"scope\":\"string\",\"named_args\":\"string\",\"path\":\"string\",\"doc\":\"string\",\"doc_format\":\"string\"}"; done
```

Actual state:
![rfhub_bug](https://user-images.githubusercontent.com/35737166/63187707-d46f4980-c05f-11e9-8b72-b6afad0d7ca8.png)

**Comment by MaciejWiczk** [comment]
I think this is due to limit coming from 
https://github.com/pbylicki/rfhub-new/blob/master/rfhub2/ui/ui_router.py#L22
and directly from
https://github.com/pbylicki/rfhub-new/blob/b74ccf242687e6450cb86e755dd03530d07c0890/rfhub2/db/repository/collection_repository.py#L24

**Comment by MaciejWiczk** [comment]
@pbylicki how we should proceed with this one? Should paging be added? This might be good for left panel, but start page is also suffering from this one.

**Comment by pbylicki** [comment]
@MaciejWiczk I am playing around with new, React-based version of frontend reading data from API. I would prefer to address this issue there.

**Comment by MaciejWiczk** [comment]
> @MaciejWiczk I am playing around with new, React-based version of frontend reading data from API. I would prefer to address this issue there.

I was wondering what occupied You :)
