### ISSUE TITLE
add possibility to import installed libraries using name instead of full path

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#342]
Currently when one wants to import python package that is installed, have to provide full package installation directory, using ie:
```
python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib()+'\SeleniumLibrary')"
```
This could be enhanced to use only module name, and let rfhub do the rest of the work.

**Comment by MarcinMaciaszek** [comment]
@MaciejWiczk
I can take this issue if you want :)
Should it check first if the path exists if not look for this path based on library name?

**Comment by MaciejWiczk** [comment]
@MarcinMaciaszek, this issue is in PR, but if You would like to continue this one, feel free to do so :)
