### ISSUE TITLE
RFHub to use tags for filtering like robot

### ISSUE THREAD

**Issue by krysalead** [pbylicki/rfhub2#361]
Hi,

Some of the keyword I am using are not to be used directly, it would be nice to have a way to filter for instance using the tags we can put in the robot file. It won't work with python and maybe this could be done with also a filtering on python script. 
WDYT?

**Comment by MaciejWiczk** [comment]
Hi @krysalead, If I'm getting You right, You would like to exclude/include only those keywords with certain tags?

**Comment by krysalead** [comment]
Hi @MaciejWiczk indeed, I have high level keyword that should be public and some that should be private (mainly in Python) and the only way I found for now is to split the keyword in multiple files and playing with the folder structure which is not really clean.

**Comment by MaciejWiczk** [comment]
Ok, this is indeed interesting one, and it shouldn't be too hard to implement. I will investigate it :)

**Comment by krysalead** [comment]
I have tried with libdoc if it relies on the same mechanism of include and exclude tags, unfortunately not.
