### ISSUE TITLE
Add animation indicating that data is loading

### ISSUE THREAD

**Issue by pbylicki** [pbylicki/rfhub2#42]
Add spinners displayed when new/additional data is being loaded.

**Comment by MaciejWiczk** [comment]
@pbylicki I thought about this one, and I think this could be done by [circular intermediate](https://material-ui.com/components/progress/#circular-indeterminate). How do You think it should be done? I think that adding separate new component 
 `frontend/src/components/CircularIndeterminate.tsx` is the proper way. Probably some if should be added inside `frontend/src/components/CollectionList.tsx` or to loadMore() const/method(?)

**Comment by MarcinMaciaszek** [comment]
Fix merged, I'm closing it :)
