### ISSUE TITLE
Pip complain to mismatched version of robotframework 4.0.3, though it works

### ISSUE THREAD

**Issue by MrBIN89** [pbylicki/rfhub2#442]
I installed rfhub2 to my environment, like:
`pip install rfhub2 -U`
`pip install robotframework==4.0.3` <= exactly this version I use in my project
After that 
`pip check` complains:
> rfhub2 0.28 has requirement robotframework<=3.2.2,>=3.0.0, but you have robotframework 4.0.3

Though it works - I can run the server and populate it.

I found several PRs that should bump RF needed version:
* https://github.com/pbylicki/rfhub2/pull/373
* https://github.com/pbylicki/rfhub2/pull/395
* https://github.com/pbylicki/rfhub2/pull/404
* https://github.com/pbylicki/rfhub2/pull/431

It looks like the latest version of rfhub2  (0.28 at this moment for me) supports the RF 4.0.3, but for some reasons the correct versions info hasn't been provided to pip manager.

**Comment by MaciejWiczk** [comment]
Hi @MrBIN89, it's a bit more complex. A [PR](https://github.com/pbylicki/rfhub2/pull/440) for updating RfHub2 to handle RFWK 4.0+ is in code review, and I will finish it this weekend. With that, there would be all features needed for handling RFWK changes, such as reading executions statistics, and getting them for embedded keywords.
This was the reason to limit supported version to 3.2.2. I also planned it to finish way sooner, but I lacked necessary time to do that.

**Comment by MaciejWiczk** [comment]
@MrBIN89 it took me longer, but everything should be ok now
