### ISSUE TITLE
clearing the already loaded collections and keywords

### ISSUE THREAD

**Issue by divakar5** [pbylicki/rfhub2#458]
Hi,

I tried to understand the rfhub2 project regarding the smart documentation of keywords. I installed rfhub2 via pip and setup the localhost:8000 . Now I have 100+ collections in my localhost and I want to remove them all and start from fresh but not sure how to do this. I request you to please help me in this regard.

Thanks

**Comment by MaciejWiczk** [comment]
Hi @divakar5, 

You can do it in three ways:

- You can go to SWagger -> `localhost:8000/docs` and trigger`delete` on `collections:
![image](https://user-images.githubusercontent.com/35737166/164202384-ef608ef8-f865-41e6-90ed-ed62700afbba.png)
You will be asked for credentials, default is `rfhub:rfhub`
- You can run cli using insert mode, and providing no collection to the path ie. `rfhub2-cli --no-installed-keywords --load-mode=insert 'path_to_no_library'` 
- You can delete `.db` file which will be recreated in a place where You started rfhub2 server

**Comment by divakar5** [comment]
Thank you! it worked
