### ISSUE TITLE
Rfhub2 could keep all collections until load of rfhub2-cli is finished

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#64]
Currently rfhub2-cli deletes all collections with keywords ant then starts with app population. In environment that has a lot of collections and keywords, this results in service temporarly showing only some of them. 

- This could be aided by creating temporary table for collections/keywords, and switching them when rfhub2-cli is done. This would require to add (private?) endpoint triggering tables switch.

- Alternatively app could delete keywords and collections from original tables, that are not in temporary ones (probably by checking names and paths of collections, or versions, then comparing keywords inside collections) and then doing upsert with SQL merge.

- Last option is to use update endpoint, for both collections and keywords

First way seems easier than second, and third seems like cleanes solution. @pbylicki what do You think?

**Comment by pbylicki** [comment]
I think it would be best to determine on the client side which collections or keywords should be added/updated and do it using existing api. there should be optional way of deleting items that are not present in new data load, but it should be explicitly selected by the user
