### ISSUE TITLE
Add new tech for pipeline

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#65]
After having unittests and functional tests integrated into CICD we can think of using couple of nice tools that github provides:

- [DependaBot](https://github.com/marketplace/dependabot-preview) to check for updates and their compatibility. This will be nicely checked by pipeline.
- [ReportCi](https://github.com/marketplace/report-ci) - tool for marking which test failed on PR, and also stores history of tests executions. Unfortunately, it does not handle robot logs, but we could check if parsing them to JUnit/xUnit xml format would do the trick.

@pbylicki what do You think? Maybe You have something else in mind for project?

**Comment by pbylicki** [comment]
@MaciejWiczk If you want to set it up, go ahead. It would be nice to see it in action.

**Comment by MaciejWiczk** [comment]
@pbylicki I would love to, but I think my repository permissions/github policy would not allow that :(

**Comment by MaciejWiczk** [comment]
I forked a repo, and did some checks. Dependabot works like a charm, creates PR for updates it finds, and that triggers build. Setting it up requires to choose language and that's it. Suppots Python, JavaScript and docker. Regarding ReportCi, it can create robot/UnitTests statistics, but it will not annotate test code from those, thus does not seem like something we need. Sadly, there is no real alternative on GithHub for robot jenkins plugin :(
@pbylicki, If you had some spare time, to install dependabot, that would be nice.

**Comment by pbylicki** [comment]
@MaciejWiczk I have seen the dependabot PR and merge it. I thought that you were able to set it up by yourself. If there are still some steps to be done, I will try to look into it.

**Comment by pbylicki** [comment]
Dependabot introduced for Python dependencies. I disabled it for JS dependencies because CI currently does not build/test JS code.
