### ISSUE TITLE
Extending Rfhub2 with analytics

### ISSUE THREAD

**Issue by MaciejWiczk** [pbylicki/rfhub2#67]
Currently Rfhub is doing it's job being a keyword interactive search app. What seems like natural continuation is providing users with some analytics data from tests executions:

- how many times each library/keywords were used. This could help to identify non-used collections, that could be removed, and heavy used collections, that could be converted into library, refactored etc.
- what are average times of keyword execution, so it may be refactored and improved if it's slow.

Implementing such changes would require:

Changes on backaed:
- new package, something like DBBot, but just for keyword statistics, 

Changes on frontend:
- first page - more columns in table, new column would show how many times library was used (sum of keywords usage from this library), maybe with some visual indicator, like progressbar.
- changes on library details page, with number of keyword execution times, visual indicator and average keyword execution time.
- changes to tables, so they can be sorted by each column.

@pbylicki, what do You think about that?

**Comment by pbylicki** [comment]
Good idea, I think that the best idea would be to create the api for receiving required statistics and use dbbot for gathering and sending statistics. Maybe dbbot could be made an optional dependency of rfhub cli and provide some wrapper on existing dbbot functionality with additional mechanism of sending statistics based on the dbbot run. I would need to look again into dbbot to see how it works with your requirements, but it seems that it should have what we need.

**Comment by MaciejWiczk** [comment]
I've taken a look at Dbbot and have two general thoughts:

- (probably) many people already use dbbot, so it would not require additional scripts added to workflows/CICDs, but it's gathering more data that we actually need for analytics
- using custom script would provide unified interface and be probably faster. Amount of code to extract and process `Collection.Keyword` with elapsed time and number of times it was used is around 20 lines. 
- [this project](https://github.com/adiralashiva8/robotframework-metrics) is using robot framework API, but I think it might be similar to Dbbot in performance aspect.

Regarding addition endpoint for stats - definetely, and a separate table for results. Probably app shouldn't display old results, but (configurable?) data for X last days. This could be handled easely by SQLalchemy query where data would be joined and filtered. 

- Joining data might be a bit tricky for keywords with embedded parameters ie `Login To App As ${User}`. This syntax appears in rfhub, but in output.xml it would appear as `Login To App As TestUser`
- from output.xml we could extract keyword name and collection name, but those are not guaranteed unique across repository, so I guess we would end up with duplicating data a bit. Lets imagine having `keyword.robot` collection, with `Login To App` keyword. If other repo/project has similar resource file with same keyword, it's tricky (impossible, without full paths) to match them right.

**Comment by MaciejWiczk** [comment]
I did some digging, and it would be best to use robotframework.api as in [here](https://gist.github.com/adiralashiva8/c6a524c554da8e2b414fe6342d50785f). 
it resolves all the embedded arguments inside keywords names, so that we have data consistent with what we already have in Rfhub documentation part. `kw.name` contains library/resource file name and keyword name like this: `BuiltIn.Log`.

**Comment by pbylicki** [comment]
@MaciejWiczk looks good. Besides of  the keyword statisics that you listed above. I was wondering if you would like to have something like a list of test cases using particular keyword, so it could be displayed for example in a modal window when user selects this option for the keyword. Could be something like suite name/test name/last recorded date as this data should be available when reading output file. What do you think?

**Comment by MaciejWiczk** [comment]
@pbylicki, this is nice idea. I did some statistics on corporate repo, and amount of used keywords is surprisingly large. Just one project varies between 3 000 and over 30 000 non-unique keyword calls. With this in mind, storing all of the data can be cumbersome. We could use some dict/dimensions in db with unique keyword/library names mapped to ids (diffrent one form docs tables, since those ids might change every now and then) to save space and computation time, but in the end we should have some cleanups after some time period. We could use our robot tests output.xml as baseline for development and testing purposes. I will prepare some stats later on with robot output.

**Comment by MaciejWiczk** [comment]
@pbylicki I have some thoughts and questions to You regarding this one:

- For sure we will need new table for statistics. Should it be done via migration using ie. Alembic?
- Aggregated statistics should be send to some dedicated endpoints, one for keywords data, and one for libraries data (aggregattion of usage times of all keywords from library)
- combining documentation with execution times.  This is getting complicated for me. I guess that
[this](https://github.com/pbylicki/rfhub2/blob/master/rfhub2/db/repository/keyword_repository.py#L39) will change into join of collection, keywords and new statistics table. Last one should be a group by to extract summary data from many output.xml. Question is, should we adapt current keyword/collection endpoint to add new data, or should they be sent by a separate endpoint with statistics? I think that extending current one would be less problematic, but I would like to hear your thoughts on that.

**Comment by pbylicki** [comment]
@MaciejWiczk 
1. If we will end up with just adding a new table, then SQLAlchemy should handle it. If we would need to add columns to existing ones, then we would need to create migrations and alembic would be the first choice to check.
2. As far as I see it now, retrieving libraries and keyword documentation are separate flows relying on different input and producing different data. I would add separate endpoints for statistics CRUD operations. We could also extend existing keyword and library GET endpoints to include appropriate statistics, maybe in such a way that user needs to call explicitly to get this extended data.
Since sending execution statistics and keyword documentation can happen independently and also documentation update may result in deleting and recreating documentation records, I would not create a strict relation between statistics and documentation records and just filter statistics by library and keyword name on request. The case when we rename the keyword or library shouldn't have a great impact since we assume that statistics will have limited time to live but we can also consider adding an endpoint/CLI for renaming statistics records for some keyword/library.
